CI step didn't like this
```
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
Error: The process '/home/runner/_work/_tool/node/20.18.1/x64/bin/yarn' failed with exit code 1
```